---
- name: Create/open LUKS and mount /data using explicit keyfile
  hosts: all
  become: true

  collections:
    - ansible.posix

  vars:
    target_device: /dev/sda
    target_partition: 3
    crypt_name: data
    mount_point: /data
    luks_keyfile: /root/luks_pw.txt
    debug_keep_keyfile: false    # <--- set to true when debugging
    

  tasks:
    - name: Ensure ENCRYPT_PW is set in environment
      ansible.builtin.assert:
        that: lookup('env','ENCRYPT_PW') | length > 0
        fail_msg: "ENCRYPT_PW environment variable is not set"

    - name: Create mount point
      ansible.builtin.file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'

    - name: Write LUKS keyfile on target from controller env
      ansible.builtin.copy:
        content: "{{ lookup('env','ENCRYPT_PW') | trim }}"
        dest: "{{ luks_keyfile }}"
        owner: root
        group: root
        mode: '0600'
      no_log: true

    # ---------- LUKS format ----------
    - name: Check if target is already LUKS
      ansible.builtin.command:
        cmd: cryptsetup isLuks "{{ target_device }}{{ target_partition }}"
      register: is_luks
      failed_when: false
      changed_when: false

    - name: LUKS format device using keyfile
      ansible.builtin.command:
        cmd: >-
          cryptsetup --batch-mode luksFormat
          "{{ target_device }}{{ target_partition }}"
          --type luks2 --pbkdf argon2id
          --key-file "{{ luks_keyfile }}"
      when: is_luks.rc != 0
      no_log: true

    # ---------- Open mapper ----------
    - name: Check if mapper is already open
      ansible.builtin.stat:
        path: "/dev/mapper/{{ crypt_name }}"
      register: mapper_stat

    - name: Open LUKS mapper using keyfile
      ansible.builtin.command:
        cmd: >-
          cryptsetup --batch-mode open
          "{{ target_device }}{{ target_partition }}"
          "{{ crypt_name }}"
          --key-file "{{ luks_keyfile }}"
      when: not mapper_stat.stat.exists
      no_log: true

    # ---------- Filesystem ----------
    - name: Detect filesystem on mapper
      ansible.builtin.command:
        cmd: blkid -o value -s TYPE "/dev/mapper/{{ crypt_name }}"
      register: fs_type
      failed_when: false
      changed_when: false

    - name: Create ext4 filesystem (only if none)
      ansible.builtin.filesystem:
        fstype: ext4
        dev: "/dev/mapper/{{ crypt_name }}"
      when: fs_type.rc != 0

    # ---------- Mount ----------
    - name: Mount /data
      ansible.posix.mount:
        path: "{{ mount_point }}"
        src: "/dev/mapper/{{ crypt_name }}"
        fstype: ext4
        state: mounted
        boot: no

    - name: Check if keyfile exists
      ansible.builtin.stat:
        path: "{{ luks_keyfile }}"
      register: keyfile_stat
    
    - name: Securely delete keyfile unless debugging
      ansible.builtin.file:
        path: "{{ luks_keyfile }}"
        state: absent
      when: keyfile_stat.stat.exists and not debug_keep_keyfile

