##################################################################################################
## Tailscale
##    As per https://tailscale.com/download/linux/ubuntu-2204
##################################################################################################
- hosts: all
  become: yes
  become_method: sudo
  vars:
    # This is a bad place to put the key, even as an example.
    # could accidently be added to repo. Please remove key
    # definition to some extra-repo file like .env etc.
    #tailscale_authkey: tskey-aaaaaaaaaaaa-bbbbbbbbbbccccccddddde
    ## FIRST:  source ./secrets/setup_env.sh
    tailscale_authkey: "{{ lookup('env', 'TAILSCALE_AUTHKEY') }}"
  tasks:
  - name: Add Tailscale GPG apt Key
    apt_key:
      id: 2596A99EAAB33821893C0A79458CA832957F5868
      url: https://pkgs.tailscale.com/stable/ubuntu/jammy.gpg
      state: present
      keyring: /etc/apt/trusted.gpg.d/tailscale-archive-keyring.gpg

  - name: Add Tailscale Repository
    apt_repository:
      repo: deb [signed-by=/etc/apt/trusted.gpg.d/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu jammy main
      state: present

  - name: Install Tailscale
    apt:
      name:
        - tailscale
      state: latest
      update_cache: true

  - name: Enable tailscaled
    systemd:
      name: tailscaled
      enabled: true
      state: started

  - name: Validate tailscale_authkey
    assert:
      that:
        - tailscale_authkey is defined
        - tailscale_authkey|length >= 30
      quiet: true
      success_msg: 'TAILSCALE_AUTHKEY is valid'
    register: authorization
    ignore_errors: true

  - name: Check if tailscale is up
    command: tailscale status
    register: status
    failed_when: status.rc|int > 1
    changed_when: false

  - name: Connect machine to tailscale
    command: "tailscale up -authkey {{ tailscale_authkey }}"
    no_log: true
    when:
      - status.rc|int != 0
      - not authorization.failed
    register: tailscale_node
    changed_when: tailscale_node.rc|int == 0
